=== pantoine31/XML_project_for_University_2023_JUNE/FINAL_XML_JUNE_2023/askisiThema1.dtd
<!ELEMENT customerList (company,person*)>
<!ELEMENT company (company_info,package_offer+)>
<!ATTLIST company CompCodeNo NMTOKEN #IMPLIED>

<!ELEMENT company_info (company_name,AFM,DOY,address)>
<!ELEMENT company_name (#PCDATA)>

<!ELEMENT person_info (name,middle_name?,surname,AFM,DOY,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT middle_name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT AFM (#PCDATA)>
<!ELEMENT DOY (#PCDATA)>
<!ELEMENT address (#PCDATA)>

<!ATTLIST package_offer package_category (B_START| B_LITE | P_LITE | P_START | B_all | P_all | B_smart | P_smart) #REQUIRED>
<!ATTLIST package_offer package_id NMTOKEN #IMPLIED>

<!ELEMENT package_offer (giving+,tel_numb*,startPrice,(finalPrice|in_discount),contract_start_date,contract_end_date)>
<!ELEMENT giving (#PCDATA)>
<!ELEMENT tel_numb (#PCDATA)>
<!ELEMENT startPrice (#PCDATA)>
<!ELEMENT finalPrice (#PCDATA)>
<!ELEMENT contract_start_date (#PCDATA)>
<!ELEMENT contract_end_date (#PCDATA)>
<!ELEMENT in_discount ((discount_rate,amount_after_disccount)|(amount_after_disccount,discount_rate))>
<!ELEMENT discount_rate (#PCDATA)>
<!ELEMENT amount_after_disccount (#PCDATA)>
<!ELEMENT person (person_info,package_offer)>

<!ATTLIST person PersonCodeNo NMTOKEN #IMPLIED>
<!ATTLIST company CompCodeNo NMTOKEN #IMPLIED>

<!ATTLIST startPrice unitS NMTOKEN "euro">
<!ATTLIST startPrice forperiodS NMTOKEN "month">
<!ATTLIST finalPrice unitF NMTOKEN "euro">
<!ATTLIST finalPrice forperiodF NMTOKEN "month">

<!ATTLIST amount_after_disccount unit NMTOKEN "euro">
<!ATTLIST amount_after_disccount forperiod NMTOKEN "month">

=== pantoine31/XML_project_for_University_2023_JUNE/FINAL_XML_JUNE_2023/askisiThema1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- ERGASIA EKSAMINOU -->

<!DOCTYPE customerList SYSTEM "askisiThema1.dtd">

<customerList>
	<company CompCodeNo="5165">
		<company_info>
			<company_name></company_name>
			<AFM></AFM>
			<DOY></DOY>
			<address></address>
		</company_info>
		<package_offer package_category="B_START" package_id="325">
            <giving></giving>
            <tel_numb></tel_numb>
            <startPrice unitS="euro" forperiodS="month"></startPrice>
            <finalPrice unitF="euro" forperiodF="month"></finalPrice>
            <contract_start_date></contract_start_date>
			<contract_end_date></contract_end_date>
		</package_offer>
        <package_offer package_category="P_START" package_id="327">
            <giving></giving>
            <tel_numb></tel_numb>
            <startPrice></startPrice>
            <in_discount>
                <discount_rate></discount_rate>
                <amount_after_disccount unit="euro" forperiod="month"></amount_after_disccount>
            </in_discount>
            <contract_start_date></contract_start_date>
			<contract_end_date></contract_end_date>
		</package_offer>
	</company>
	<person PersonCodeNo="5167">
		<person_info>
			<name></name>
			<middle_name></middle_name>
			<surname></surname>
			<AFM></AFM>
			<DOY></DOY>
			<address></address>
		</person_info>
		<package_offer package_category="P_START" package_id="327">
            <giving></giving>
            <tel_numb></tel_numb>
            <startPrice></startPrice>
            <in_discount>
                <amount_after_disccount></amount_after_disccount>
                <discount_rate></discount_rate>
            </in_discount>
            <contract_start_date></contract_start_date>
			<contract_end_date></contract_end_date>
		</package_offer>
	</person>
</customerList>

=== pantoine31/XML_project_for_University_2023_JUNE/FINAL_XML_JUNE_2023/askisiThema1 - Valid.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- ERGASIA EKSAMINOU -->

<!DOCTYPE customerList SYSTEM "askisiThema1.dtd">

<customerList>
	<company CompCodeNo="5165">
		<company_info>
			<company_name>Unipi</company_name>
			<AFM>999999999</AFM>
			<DOY>ΠΕΙΡΑΙΩΣ</DOY>
			<address>ΚΑΡΑΟΛΗ ΚΑΙ ΔΗΜΗΤΡΙΟΥ</address>
		</company_info>
		<package_offer package_category="B_START" package_id="325">
            <giving>ΔΩΡΕΑΝ ΣΙΤΗΣΗ</giving>
            <tel_numb>2104142000</tel_numb>
            <startPrice unitS="euro" forperiodS="month">800</startPrice>
            <finalPrice unitF="euro" forperiodF="month">650</finalPrice>
            <contract_start_date>18-03-2002</contract_start_date>
			<contract_end_date>20-05-2025</contract_end_date>
		</package_offer>
        <package_offer package_category="P_START" package_id="327">
            <giving>ΓΡΑΦΙΣΤΙΚΗ ΥΛΗ</giving>
            <tel_numb>2104142000</tel_numb>
            <startPrice>700</startPrice>
            <in_discount>
                <discount_rate>50</discount_rate>
                <amount_after_disccount unit="euro" forperiod="month">350</amount_after_disccount>
            </in_discount>
            <contract_start_date>12-08-2004</contract_start_date>
			<contract_end_date>01-12-2024</contract_end_date>
		</package_offer>
	</company>
	<person PersonCodeNo="5167">
		<person_info>
			<name>ΙΩΑΝΝΗΣ</name>
			<middle_name>ΚΩΣΤΑΣ</middle_name>
			<surname>ΠΑΠΑΔΟΠΟΥΛΟΣ</surname>
			<AFM>111111111</AFM>
			<DOY>ΘΕΣΣΑΛΟΝΙΚΗΣ</DOY>
			<address>Λεωφόρος Νίκης</address>
		</person_info>
		<package_offer package_category="P_START" package_id="327">
            <giving>ΤΑΞΙΔΙ</giving>
            <tel_numb>6948647516</tel_numb>
            <startPrice>400</startPrice>
            <in_discount>
                <amount_after_disccount>360</amount_after_disccount>
                <discount_rate>10</discount_rate>
            </in_discount>
            <contract_start_date>25-05-2023</contract_start_date>
			<contract_end_date>27-06-2023</contract_end_date>
		</package_offer>
	</person>
</customerList>
