=== pantoine31/XML_project_for_University_2023_JUNE/FINAL_XML_JUNE_2023/HOME23_new.dtd
<!ELEMENT Epipla_Diakosmisi_AE (name,stores_list,product_categories,room_classification,special_classification,contact_details,store_hours,Services?,product_list)>
<!ATTLIST Epipla_Diakosmisi_AE number_of_products CDATA #REQUIRED>
<!ATTLIST Epipla_Diakosmisi_AE Year_opened NMTOKEN #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT stores_list (store+)>
<!ELEMENT store EMPTY>
<!ATTLIST store strid NMTOKEN #REQUIRED>
<!ATTLIST store name CDATA #REQUIRED>
<!ELEMENT product_categories (product_type+)>
<!ELEMENT product_type (#PCDATA)>
<!ATTLIST product_type prod_class_id NMTOKEN #REQUIRED>
<!ELEMENT room_classification (room_class+)>
<!ATTLIST room_classification value CDATA #REQUIRED>
<!ELEMENT room_class (#PCDATA)>
<!ATTLIST room_class class_id NMTOKEN #REQUIRED>
<!ELEMENT special_classification (special_classes)>
<!ELEMENT special_classes ((outlet,campaign)|(campaign,outlet))>
<!ELEMENT campaign EMPTY>
<!ATTLIST campaign spclass_id NMTOKEN #REQUIRED>
<!ELEMENT outlet EMPTY>
<!ATTLIST outlet spclass_id NMTOKEN #REQUIRED>

<!ELEMENT contact_details (Headquarters,stores)>
<!ELEMENT Headquarters (address,(tel|email)*)>
<!ELEMENT address ANY>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT stores (shop_store*)>
<!ELEMENT shop_store (address,(email|tel)*)>
<!ELEMENT store_hours (Day+)>
<!ELEMENT Day (#PCDATA|Timing)*>
<!ATTLIST Day day_id NMTOKEN #REQUIRED>
<!ELEMENT Timing (#PCDATA)>

<!ELEMENT Services (shipping_Charges,Assembly_Charges,Interior_Design_Charges?)>
<!ELEMENT shipping_Charges ((charges_Ath_Th,charges_other_places)|(charges_other_places,charges_Ath_Th))>
<!ELEMENT charges_Ath_Th (shipValue+)>
<!ATTLIST charges_Ath_Th shipping_until CDATA #REQUIRED>
<!ELEMENT shipValue (#PCDATA)>
<!ATTLIST shipValue ship_weight_category CDATA #REQUIRED>
<!ATTLIST shipValue shpunit (euro) #IMPLIED>
<!ELEMENT charges_other_places (shipValue+)>
<!ATTLIST charges_other_places shipping_until CDATA #REQUIRED>

<!ELEMENT Assembly_Charges (assValue*)>
<!ELEMENT assValue (#PCDATA)>
<!ATTLIST assValue assunit (euro) #IMPLIED>
<!ATTLIST assValue ass_category CDATA #REQUIRED>
<!ELEMENT Interior_Design_Charges (DesValue*)>
<!ELEMENT DesValue (#PCDATA)>
<!ATTLIST DesValue forevery CDATA "δωμάτιο" >
<!ATTLIST DesValue Des_category CDATA #REQUIRED>
<!ATTLIST DesValue dessunit (euro) #IMPLIED>

<!ELEMENT product_list (product*)>
<!ELEMENT product (product_identification,store_availability,product_descr,product_characteristics,start_value,Final_value)>
<!ATTLIST product product_id CDATA #REQUIRED>
<!ATTLIST product prod_class_id CDATA #IMPLIED>
<!ATTLIST product room_class CDATA #IMPLIED>
<!ATTLIST product spclass_id CDATA #IMPLIED>
<!ELEMENT product_identification EMPTY>
<!ATTLIST product_identification product_name CDATA #IMPLIED>
<!ATTLIST product_identification product_code CDATA #REQUIRED>
<!ELEMENT store_availability (quantity*)>
<!ELEMENT quantity (#PCDATA)>
<!ATTLIST quantity store_id CDATA #REQUIRED>
<!ELEMENT product_descr (#PCDATA)>
<!ELEMENT product_characteristics (manufacturer_country?,weight,material*,included*,not_included*,color*,(size+|Dimensions+),certified?)>
<!ELEMENT manufacturer_country (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ATTLIST weight unit_weight (kg|gr) "kg">
<!ELEMENT material (#PCDATA)>
<!ATTLIST material mtr CDATA #IMPLIED>
<!ELEMENT included (#PCDATA)>
<!ATTLIST included quantity CDATA #IMPLIED>
<!ELEMENT not_included (#PCDATA)>
<!ATTLIST not_included no_incl CDATA #IMPLIED>
<!ELEMENT color (#PCDATA|also_available_color)*>
<!ATTLIST color in CDATA #IMPLIED>
<!ELEMENT also_available_color (#PCDATA)>
<!ATTLIST also_available_color also_color CDATA #REQUIRED>
<!ELEMENT size (#PCDATA)>
<!ELEMENT Dimensions (height?,length?,width,depth*)>
<!ATTLIST Dimensions assembled_boolean (true|false) #IMPLIED>
<!ELEMENT height (#PCDATA)>
<!ATTLIST height unit_height (cm|m) "cm">
<!ELEMENT length (#PCDATA)>
<!ATTLIST length unit_length (cm|m) "cm">
<!ELEMENT width (#PCDATA)>
<!ATTLIST width unit_width (cm|m) "cm">
<!ELEMENT depth (#PCDATA)>
<!ATTLIST depth unit_depth (cm) "cm">
<!ATTLIST depth for CDATA #IMPLIED>
<!ELEMENT certified EMPTY>
<!ATTLIST certified certificate CDATA #REQUIRED>

<!ELEMENT start_value (#PCDATA|offer_rate)*>
<!ELEMENT offer_rate (#PCDATA)>
<!ATTLIST start_value valunit CDATA #IMPLIED>
<!ATTLIST start_value can_return (yes|no) #IMPLIED>
<!ATTLIST start_value can_reserved (yes|no) #IMPLIED>
<!ATTLIST start_value option_of_assembly (yes|no) #IMPLIED>
<!ATTLIST start_value is_assembled (yes|no) #IMPLIED>

<!ELEMENT Final_value  (#PCDATA|accept_doses)*>
<!ATTLIST Final_value fnlunit CDATA "euro">
<!ELEMENT accept_doses (num_doses,ammount_dose,With_credit_card?,Interest_free?)>
<!ELEMENT num_doses (#PCDATA)>
<!ELEMENT ammount_dose (#PCDATA)>
<!ELEMENT With_credit_card EMPTY>
<!ELEMENT Interest_free EMPTY>

=== pantoine31/XML_project_for_University_2023_JUNE/FINAL_XML_JUNE_2023/HOME23xml with xsl/HOME23_new.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="present5.xsl"?>

<!-- kathe fora antikathistoyme to line2 me analoga me to xml poy theloyme na trexoume--> 

<!DOCTYPE Epipla_Diakosmisi_AE SYSTEM "HOME23_new.dtd">

<Epipla_Diakosmisi_AE number_of_products="over of 2.000" Year_opened="2004">
	<name>HOME23</name>
	<stores_list>
		<store strid="1" name="HOME23 - Αθήνα (Κολωνάκι)"></store>
		<store strid="2" name="HOME23 - Αθήνα (Αεροδρόμιο)"></store>
		<store strid="3" name="HOME23 - Θεσσαλονίκη"></store>
		<store strid="4" name="HOME23 - Ιωάννινα"></store>
		<store strid="5" name="HOME23 - Λάρισα"></store>
		<store strid="6" name="HOME23 - Ξάνθη"></store>
		<store strid="7" name="HOME23 - Κέρκυρα"></store>
		<store strid="8" name="HOME23 - Καλαμάτα"></store>
		<store strid="9" name="HOME23 - Κρήτη"></store>
	</stores_list>
	<product_categories> 
		
		<product_type prod_class_id="1">Καναπέδες και πολυθρόνες</product_type>
		<product_type prod_class_id="2">Έπιπλα οργάνωσης κι αποθήκευσης</product_type>
		<product_type prod_class_id="3">Κουζίνα και Πάγκοι Κουζίνας</product_type>
		<product_type prod_class_id="4">Είδη Σερβιρίσματος</product_type>
		<product_type prod_class_id="5">Χαλιά</product_type>
		<product_type prod_class_id="6">Κρεβάτια και Στρώματα και μαξιλάρια</product_type>
		<product_type prod_class_id="7">Ντουλάπες</product_type>
		<product_type prod_class_id="8">Βρεφικά -Παιδικά Είδη και έπιπλα</product_type>
		<product_type prod_class_id="9">Λευκά είδη</product_type>
		<product_type prod_class_id="10">Φωτισμός</product_type>
		<product_type prod_class_id="11">Γραφεία</product_type>
		<product_type prod_class_id="12">Συρταριέρες</product_type>
		<product_type prod_class_id="13">Τραπέζια</product_type>
		<product_type prod_class_id="14">Είδη Κουζίνας</product_type>
		<product_type prod_class_id="15">Σκαμπό και πάγκοι κουζίνας</product_type>
		<product_type prod_class_id="16">Κομοδίνα</product_type>
		<product_type prod_class_id="17">Καρέκλες</product_type>
		<product_type prod_class_id="18">Διακόσμηση Τοίχου και καθρέφτες</product_type>
		<product_type prod_class_id="19">Διακοσμητικά, κεριά και φυτά</product_type>
		<product_type prod_class_id="20">Κήπος και εξωτερικοί χώροι</product_type>
		<product_type prod_class_id="21">Είδη μπάνιου</product_type>
		<product_type prod_class_id="22">Μπουφέδες</product_type>
		<product_type prod_class_id="23">Εργαλεία και εξαρτήματα</product_type>
		<product_type prod_class_id="24">Χόμπι και ασφάλεια</product_type>
		<product_type prod_class_id="25">Κουρτίνες</product_type>
		<product_type prod_class_id="26">Ριχτάρια </product_type>     
	</product_categories>
	<room_classification value="">
		<room_class class_id="1">Υπνοδωμάτιο (bedroom)</room_class>
		<room_class class_id="2">Μπάνιο (bathroom)</room_class>
		<room_class class_id="3">Δωμάτιο Γραφείου (office)</room_class>
		<room_class class_id="4">Καθιστικό/Σαλόνι (living_room)</room_class>
		<room_class class_id="5">Τραπεζαρία (dining_room)</room_class>
		<room_class class_id="6">Κουζίνα (kitchen)</room_class>
		<room_class class_id="7">Παιδικό δωμάτιο (kids_room)</room_class>
		<room_class class_id="8">Εξωτερικοί Χώροι/Κήπος (outdoor) </room_class>
		<room_class class_id="9">Χώρος Αποθήκευσης (Αποθήκη)/Γκαράζ (storage_room)</room_class>
	</room_classification>
	<special_classification>
		<special_classes>
			<campaign spclass_id="1"></campaign>
			<outlet spclass_id="2"></outlet>
		</special_classes>
	</special_classification>
	<contact_details>
		<Headquarters>
			<address>Παπαρηγοπούλου 345, Αθήνα, ΕΛΛΑΔΑ, 100-45</address>
			<tel>+30 210 12345678</tel>
			<email>xyz@outl.HOME23.com</email>
		</Headquarters>
		<stores>
			<shop_store>
				<address>xyzw 99, Αθήνα,ΕΛΛΑΔΑ, 100-54</address>
				<tel>+30 210 213359778</tel>
				<email>kolonaki@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Ελ. Βενιζέλου 7, Παιανία,ΕΛΛΑΔΑ, 102-33</address>
				<tel>+30 210 133669785</tel>
				<email>airport@outl.HOME23.comm</email>
			</shop_store>
			<shop_store>
				<address> Τσιμισκί 200, Θεσσαλονίκη,ΕΛΛΑΔΑ, 456-32</address>
				<tel>+30 2310 999669321</tel>
				<email>Thessaloniki@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Σουλίου 67, Ιωάννινα,ΕΛΛΑΔΑ, 323-11</address>
				<tel>+30 26510-432990321</tel>
				<email>Ioannina@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Ασκληπιού 119, Λάρισα,ΕΛΛΑΔΑ, 412-22</address>
				<tel>+30 2410 241111</tel>
				<email>larissa@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Φιλελλήνων 10, Κέρκυρα,ΕΛΛΑΔΑ, 491-31</address>
				<tel>+30 26610 301158</tel>
				<email>kerkira@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Αριστομένους 115, Καλαμάτα,ΕΛΛΑΔΑ, 241-00</address>
				<tel>+30 27210-97967</tel>
				<email>kalamata@outl.HOME23.com</email>
			</shop_store>
			<shop_store>
				<address>Λεωφ. Κνωσού 13, Ηράκλειο,ΕΛΛΑΔΑ, 714-10</address>
				<tel>+30 2810-211111</tel>
				<email>creta@outl.HOME23.com</email>
			</shop_store>
		</stores>
	</contact_details>
	<store_hours>
		<Day day_id="1">Δευτέρα
			<Timing>9:00 am - 15:00 pm</Timing>
		</Day>
		<Day day_id="2">Τρίτη		
			<Timing>9:00 am - 15:00 pm και 17:00 pm - 21:00 pm</Timing>
		</Day>
		<Day day_id="3">Τετάρτη
			<Timing>9:00 am - 15:00 pm</Timing>
		</Day>
		<Day day_id="4">Πέμπτη		
			<Timing>9:00 am - 15:00 pm και 17:00 pm - 21:00 pm</Timing>
		</Day>
		<Day day_id="5">Παρακσευή		
			<Timing>9:00 am - 21:00 pm</Timing>
		</Day>
		<Day day_id="6">Σάββατο		
			<Timing>9:00 am - 18:00 pm</Timing>
		</Day>
		<Day day_id="7">Κυριακή		
			<Timing>Κλειστά</Timing>
		</Day>
	</store_hours>
	<Services>
		<shipping_Charges>
			<charges_Ath_Th shipping_until="4 εργάσιμων ημερών" >
				<shipValue ship_weight_category="0 - 15 κιλά" shpunit="euro">4.50</shipValue>
				<shipValue ship_weight_category="15.01 - 35 κιλά" shpunit="euro">9.00</shipValue>
				<shipValue ship_weight_category="35.01 - 65 κιλά" shpunit="euro">19.00</shipValue>
				<shipValue ship_weight_category="65.01 - 100 κιλά" shpunit="euro">29.00</shipValue>
				<shipValue ship_weight_category="100.01 - 200 κιλά" shpunit="euro">49.00</shipValue>
				<shipValue ship_weight_category="200.01 - 400 κιλά" shpunit="euro">59.00</shipValue>
				<shipValue ship_weight_category="> 400.01 κιλά" shpunit="euro">69.00</shipValue>
			</charges_Ath_Th>
			<charges_other_places shipping_until="8 εργάσιμων ημερών">
				<shipValue ship_weight_category="0 - 15 κιλά" shpunit="euro">7.50</shipValue>
				<shipValue ship_weight_category="15.01 - 35 κιλά" shpunit="euro">11.50</shipValue>
				<shipValue ship_weight_category="35.01 - 65 κιλά" shpunit="euro">33.00</shipValue>
				<shipValue ship_weight_category="65.01 - 100 κιλά" shpunit="euro">58.00</shipValue>
				<shipValue ship_weight_category="100.01 - 200 κιλά" shpunit="euro">78.00</shipValue>
				<shipValue ship_weight_category="200.01 - 400 κιλά" shpunit="euro">95.00</shipValue>
				<shipValue ship_weight_category="> 400.01 κιλά" shpunit="euro">105.00</shipValue>
			</charges_other_places>
		</shipping_Charges>
		<Assembly_Charges>
			<assValue assunit="euro" ass_category="Προϊόντα αξίας από  0.01 - 2.500 ευρώ:">10% της αξίας του προϊόντος που θέλετε να συναρμολογήσετε</assValue> 
			<assValue ass_category="Προϊόντα αξίας > 2.500 Ευρώ:">δωρεάν</assValue>
		</Assembly_Charges>
		<Interior_Design_Charges>
			<DesValue forevery="δωμάτιο"  Des_category="&lt; 50m2" dessunit="euro">200</DesValue>
			<DesValue forevery="δωμάτιο" Des_category=">=50m2">300</DesValue>
		</Interior_Design_Charges>
	</Services>
	<product_list>
		<product product_id="1" prod_class_id="21 9" room_class="2" spclass_id="2">
			<product_identification product_code="H28K4741L" product_name="Μπουρνούζι LERUM"/>
			<store_availability>
				<quantity store_id="3">10</quantity>	
				<quantity store_id="2">2</quantity>
			</store_availability>
			<product_descr>
			Πολύ απαλό και απορροφητικό μπουρνούζι, υφασμένο από 100% βαμβάκι και σε μοναδικές αποχρώσεις που ταιριάζουν και κολακεύουν τον καθένα.
			Μοναδικής ποιότητας μπουρνούζι με κουκούλα, διαθέσιμο σε 10 αποχρώσεις.
			</product_descr>
			<product_characteristics>
				<manufacturer_country>Ελλάδα</manufacturer_country>
				<weight unit_weight="gr">480</weight>
				<material mtr="1">100% Βαμβάκι</material>
				<color>Γκρι</color>
				<size>L</size>
				<size>XL</size>
				<certified certificate="STANDARD 100 by OEKO-TEX®"></certified>
			</product_characteristics>
			<start_value valunit="euro" can_return="no">19.99
				<offer_rate>33%</offer_rate>
			</start_value>
			<Final_value fnlunit="euro">13.50</Final_value>
		</product>
		<product product_id="2" prod_class_id="11" room_class="3">
			<product_identification product_code="K33J4755J" product_name="Γραφείο DERUP 40x100 λευκό"/>
			<store_availability>
				<quantity store_id="3">3</quantity>
				<quantity store_id="1">2</quantity>
				<quantity store_id="4">1</quantity>
				<quantity store_id="5">3</quantity>
				<quantity store_id="8">2</quantity>
				<quantity store_id="9">2</quantity>
			</store_availability>
			<product_descr>Η σειρά εργασιακών γραφείων DERUP, είναι ο απόλυτος συνδυασμός απαλών φορμών, φυσικών υλικών και χρωμάτων,
			για ένα φιλικό προς τον χρήστη εργασιακό περιβάλλον.Καλύπτει άψογα πολλές τις ανάγκες των χώρων εργασίας,
			αναδεικνύοντας τον χώρο με τον αυθεντικό αλλά ταυτόχρονα και εντυπωσιακό σχεδιασμό της.</product_descr>
			<product_characteristics>
				<manufacturer_country>Ελλάδα</manufacturer_country>
				<weight unit_weight="kg">15</weight>
				<material mtr="1">Μελαμίνη</material>
				<material mtr="2">Μοριοσανίδα</material>
				<material mtr="3">HDF</material>
				<material mtr="4">Πλαστικό</material>
				<included quantity="1">Συρτάρι</included>
				<included quantity="1">Φρένο Συρταριού</included>
				<color>Λευκό</color>
				<Dimensions assembled_boolean="true">
					<height unit_height="cm">75</height>
